### ISSUE TITLE
Fix sourcing for makechrootpkg

### ISSUE THREAD

**Issue by Martchus** [hipersayanX/ArchPackages#2]
When using makechrootpkg it doesn't work to source files outside of the functions like this: https://github.com/hipersayanX/ArchPackages/blob/master/android-zlib/PKGBUILD#L4

Moving this line into the `prepare`, `build` and `package` functions seems to work. Would this change be o.k. for you? Having the source line 3 times instead of just once is annoying but I would prefer if that official way of creating Arch Linux package would be supported.

**Comment by hipersayanX** [comment]
Yes, I think that is a good idea.

**Comment by hipersayanX** [comment]
Merge accepted, thanks!
